osx_image: xcode9
language: swift

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - XCODE_PROJECT=./Demo/CWShareViewDemo.xcodeproj
  matrix:
    - SCHEME="CWShareViewDemo"

before_install:
  - gem install xcpretty --quiet

script:
  - set -o pipefail
  - xcodebuild -project "$XCODE_PROJECT" -scheme "$SCHEME" -configuration Release clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c

after_success:
  - sleep 5
